### ISSUE TITLE
you stole kyle's walk sim and reuploaded it as your  own

### ISSUE THREAD

**Issue by cheezygt** [adrielgamer0805/GTAG-WALK-SIM#1]

**Comment by GBCVR** [comment]
whos kyle you mean @KyleTheScientist

**Comment by Cheezy-bip** [comment]
yes

**Comment by CrazyManYTVR** [comment]
I didn't steal anything

**Comment by cheezygt** [comment]
skid

**Comment by adrielgamer0805** [comment]
EVERYONE CHECK THE READ ME! I HAVE CREDITS THERE.

**Comment by Zyverianox** [comment]
https://github.com/Zyverianox/WalkSim-Reborn go here

**Comment by cheezygt** [comment]
> https://github.com/Zyverianox/WalkSim-Reborn go here

its been a year vro 😭 
also just to make sure this only works in modded lobbies?

**Comment by Zyverianox** [comment]
> > https://github.com/Zyverianox/WalkSim-Reborn go here
> 
> its been a year vro 😭 also just to make sure this only works in modded lobbies?

nah it works with public

**Comment by Zyverianox** [comment]
> > https://github.com/Zyverianox/WalkSim-Reborn go here
> 
> its been a year vro 😭 also just to make sure this only works in modded lobbies?

or maybe ur just a dumbass that doesn't know how to use it 😭 🙏

**Comment by cheezygt** [comment]
> > > https://github.com/Zyverianox/WalkSim-Reborn go here
> > 
> > 
> > its been a year vro 😭 also just to make sure this only works in modded lobbies?
> 
> or maybe ur just a dumbass that doesn't know how to use it 😭 🙏

how am i the dumbass??? your the one that made the cheat

**Comment by Zyverianox** [comment]
> > > > https://github.com/Zyverianox/WalkSim-Reborn go here
> > > 
> > > 
> > > its been a year vro 😭 also just to make sure this only works in modded lobbies?
> > 
> > 
> > or maybe ur just a dumbass that doesn't know how to use it 😭 🙏
> 
> how am i the dumbass??? your the one that made the cheat

what cheat lmao walksim??? its a mod 😭 its a fucking DLL u dumbass 💀 🙏

**Comment by cheezygt** [comment]
i think its safe to assume you also skidded walksimreborn

**Comment by Zyverianox** [comment]
> i think its safe to assume you also skidded walksimreborn

😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf

**Comment by Zyverianox** [comment]
> > > i think its safe to assume you also skidded walksimreborn
> > 
> > 
> > 😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf
> 
> bro u "made" a cheat, and you dont know whats a cheat, most normal people would assume its stolen

okay so walksim is a cheat? alright and its also stolen right? and also idk why ur saying skidded and saying stolen to other repository when you probably don't have the game bruh

**Comment by Zyverianox** [comment]
and to use the "cheat" you need to have the game installed which  it cost money 😭 and also if it was a cheat it would be a exe file 😭

**Comment by Zyverianox** [comment]
like go back to playing Minecraft 😭

**Comment by Zyverianox** [comment]
also the word  "skid" in 25 💔

**Comment by Zyverianox** [comment]
wild man 😭

**Comment by cheezygt** [comment]
> > > > i think its safe to assume you also skidded walksimreborn
> > > 
> > > 
> > > 😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf
> > 
> > 
> > bro u "made" a cheat, and you dont know whats a cheat, most normal people would assume its stolen
> 
> okay so walksim is a cheat? alright and its also stolen right? and also idk why ur saying skidded and saying stolen to other repository when you probably don't have the game bruh

the original walksim by kyle isnt a cheat, "your" version is. and i dont understand why you would assume i dont have the game. cheats dont neccesarily have to be a executable, your cheat is a dll because thats how bepis injector extensible loads mods.

**Comment by Zyverianox** [comment]
> > > > > i think its safe to assume you also skidded walksimreborn
> > > > 
> > > > 
> > > > 😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf
> > > 
> > > 
> > > bro u "made" a cheat, and you dont know whats a cheat, most normal people would assume its stolen
> > 
> > 
> > okay so walksim is a cheat? alright and its also stolen right? and also idk why ur saying skidded and saying stolen to other repository when you probably don't have the game bruh
> 
> the original walksim by kyle isnt a cheat, "your" version is. and i dont understand why you would assume i dont have the game. cheats dont neccesarily have to be a executable, your cheat is a dll because thats how bepis injector extensible loads mods.

yap yap yap I ain't reading all of that 😭

**Comment by cheezygt** [comment]
> > > > > > i think its safe to assume you also skidded walksimreborn
> > > > > 
> > > > > 
> > > > > 😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf
> > > > 
> > > > 
> > > > bro u "made" a cheat, and you dont know whats a cheat, most normal people would assume its stolen
> > > 
> > > 
> > > okay so walksim is a cheat? alright and its also stolen right? and also idk why ur saying skidded and saying stolen to other repository when you probably don't have the game bruh
> > 
> > 
> > the original walksim by kyle isnt a cheat, "your" version is. and i dont understand why you would assume i dont have the game. cheats dont neccesarily have to be a executable, your cheat is a dll because thats how bepis injector extensible loads mods.
> 
> yap yap yap I ain't reading all of that 😭

you dont have to?

**Comment by Zyverianox** [comment]
> > > > > > > i think its safe to assume you also skidded walksimreborn
> > > > > > 
> > > > > > 
> > > > > > 😭 skidded? how am I'm skidded be grateful that it works you dumbass 😭 cope mf
> > > > > 
> > > > > 
> > > > > bro u "made" a cheat, and you dont know whats a cheat, most normal people would assume its stolen
> > > > 
> > > > 
> > > > okay so walksim is a cheat? alright and its also stolen right? and also idk why ur saying skidded and saying stolen to other repository when you probably don't have the game bruh
> > > 
> > > 
> > > the original walksim by kyle isnt a cheat, "your" version is. and i dont understand why you would assume i dont have the game. cheats dont neccesarily have to be a executable, your cheat is a dll because thats how bepis injector extensible loads mods.
> > 
> > 
> > yap yap yap I ain't reading all of that 😭
> 
> you dont have to?

yeah and why say skid, and stolen when Kyle doesn't even update it anymore 😭

**Comment by Zyverianox** [comment]
like think 💀 🙏

**Comment by cheezygt** [comment]
> like think 💀 🙏

you didnt credit kyle, and said its the "official"

**Comment by Zyverianox** [comment]
> > like think 💀 🙏
> 
> you didnt credit kyle, and said its the "official"

so if I credit him we stop the beef?

**Comment by cheezygt** [comment]
> > > like think 💀 🙏
> > 
> > 
> > you didnt credit kyle, and said its the "official"
> 
> so if I credit him we stop the beef?

yeah and also its unofficial

**Comment by Zyverianox** [comment]
e

> > > > like think 💀 🙏
> > > 
> > > 
> > > you didnt credit kyle, and said its the "official"
> > 
> > 
> > so if I credit him we stop the beef?
> 
> yeah and also its unofficial

nah its official now 🔥

**Comment by Zyverianox** [comment]
be grateful bro 💔

**Comment by Zyverianox** [comment]
https://github.com/Zyverianox/WalkSim-Reborn
