### ISSUE TITLE
terms and conditions screen

### ISSUE THREAD

**Issue by bob121613** [adrielgamer0805/GTAG-WALK-SIM#2]
Won't work most likely because the terms and conditions screen. Btw hell you mean "hold tab and hover over a mode and release tab"? where DO I hover AND WHAT DO I USE TO HOVER?!?! THE GORILLA? MOUSE? I DON'T GIVE A SH-

**Comment by bob121613** [comment]
nvm btw it wont let me move

**Comment by adrielgamer0805** [comment]
this might be broken lol

**Comment by Zyverianox** [comment]
https://github.com/Zyverianox/WalkSim-Reborn
