### ISSUE TITLE
how do i download the file?

### ISSUE THREAD

**Issue by Foxinsocks14** [adrielgamer0805/GTAG-WALK-SIM#3]
i dont know how to download the file and does this work? or is it broken.

**Comment by bob121613** [comment]
click the dll, then "download RAW file".
i'm guessing you know how to install the mod

**Comment by adrielgamer0805** [comment]
> click the dll, then "download RAW file". i'm guessing you know how to install the mod

Thx

**Comment by Zyverianox** [comment]
> i dont know how to download the file and does this work? or is it broken.

https://github.com/Zyverianox/WalkSim-Reborn just use this
